spring:
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}
    virtual-host: /

wms:
  rabbitmq:
    exchange: wcs.topic
    queue:
      inbound-complete: wms.queue.inbound.complete
      outbound-cmd-ack: wms.queue.outbound.cmd.ack
    routing-key:
      inbound-cmd: wms.inbound.cmd
      inbound-complete: wcs.inbound.complete
      inbound-cancel: wms.inbound.cancel
      outbound-cmd: wms.outbound.cmd
      outbound-cmd-ack: wcs.outbound.cmd.ack

logging:
  level:
    com.example.wmsmock: INFO
